/*
 * Geocoding and Search API v7
 *
 * This document describes the Geocoding and Search API.
 *
 * API version: 7.78
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package here

import (
	"encoding/json"
)

type OneOfAutosuggestEntityResultItemAutosuggestQueryResultItem string
// OpenSearchAutosuggestResponse struct for OpenSearchAutosuggestResponse
type OpenSearchAutosuggestResponse struct {
	// The results are presented as a JSON list of candidates in ranked order (most-likely to least-likely) based on the matched location criteria.
	Items []OneOfAutosuggestEntityResultItemAutosuggestQueryResultItem `json:"items"`
	// Suggestions for refining individual query terms
	QueryTerms []QueryTermResultItem `json:"queryTerms"`
}

// NewOpenSearchAutosuggestResponse instantiates a new OpenSearchAutosuggestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenSearchAutosuggestResponse(items []OneOfAutosuggestEntityResultItemAutosuggestQueryResultItem, queryTerms []QueryTermResultItem, ) *OpenSearchAutosuggestResponse {
	this := OpenSearchAutosuggestResponse{}
	this.Items = items
	this.QueryTerms = queryTerms
	return &this
}

// NewOpenSearchAutosuggestResponseWithDefaults instantiates a new OpenSearchAutosuggestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenSearchAutosuggestResponseWithDefaults() *OpenSearchAutosuggestResponse {
	this := OpenSearchAutosuggestResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *OpenSearchAutosuggestResponse) GetItems() []OneOfAutosuggestEntityResultItemAutosuggestQueryResultItem {
	if o == nil  {
		var ret []OneOfAutosuggestEntityResultItemAutosuggestQueryResultItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *OpenSearchAutosuggestResponse) GetItemsOk() (*[]OneOfAutosuggestEntityResultItemAutosuggestQueryResultItem, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *OpenSearchAutosuggestResponse) SetItems(v []OneOfAutosuggestEntityResultItemAutosuggestQueryResultItem) {
	o.Items = v
}

// GetQueryTerms returns the QueryTerms field value
func (o *OpenSearchAutosuggestResponse) GetQueryTerms() []QueryTermResultItem {
	if o == nil  {
		var ret []QueryTermResultItem
		return ret
	}

	return o.QueryTerms
}

// GetQueryTermsOk returns a tuple with the QueryTerms field value
// and a boolean to check if the value has been set.
func (o *OpenSearchAutosuggestResponse) GetQueryTermsOk() (*[]QueryTermResultItem, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.QueryTerms, true
}

// SetQueryTerms sets field value
func (o *OpenSearchAutosuggestResponse) SetQueryTerms(v []QueryTermResultItem) {
	o.QueryTerms = v
}

func (o OpenSearchAutosuggestResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	if true {
		toSerialize["queryTerms"] = o.QueryTerms
	}
	return json.Marshal(toSerialize)
}

type NullableOpenSearchAutosuggestResponse struct {
	value *OpenSearchAutosuggestResponse
	isSet bool
}

func (v NullableOpenSearchAutosuggestResponse) Get() *OpenSearchAutosuggestResponse {
	return v.value
}

func (v *NullableOpenSearchAutosuggestResponse) Set(val *OpenSearchAutosuggestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenSearchAutosuggestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenSearchAutosuggestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenSearchAutosuggestResponse(val *OpenSearchAutosuggestResponse) *NullableOpenSearchAutosuggestResponse {
	return &NullableOpenSearchAutosuggestResponse{value: val, isSet: true}
}

func (v NullableOpenSearchAutosuggestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenSearchAutosuggestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


