/*
 * Geocoding and Search API v7
 *
 * This document describes the Geocoding and Search API.
 *
 * API version: 7.78
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package here

import (
	"encoding/json"
)

// OpenSearchAutocompleteResponse struct for OpenSearchAutocompleteResponse
type OpenSearchAutocompleteResponse struct {
	// The results are presented as a JSON list of candidates in ranked order (most-likely to least-likely) based on the matched location criteria.
	Items []AutocompleteResultItem `json:"items"`
}

// NewOpenSearchAutocompleteResponse instantiates a new OpenSearchAutocompleteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenSearchAutocompleteResponse(items []AutocompleteResultItem, ) *OpenSearchAutocompleteResponse {
	this := OpenSearchAutocompleteResponse{}
	this.Items = items
	return &this
}

// NewOpenSearchAutocompleteResponseWithDefaults instantiates a new OpenSearchAutocompleteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenSearchAutocompleteResponseWithDefaults() *OpenSearchAutocompleteResponse {
	this := OpenSearchAutocompleteResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *OpenSearchAutocompleteResponse) GetItems() []AutocompleteResultItem {
	if o == nil  {
		var ret []AutocompleteResultItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *OpenSearchAutocompleteResponse) GetItemsOk() (*[]AutocompleteResultItem, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *OpenSearchAutocompleteResponse) SetItems(v []AutocompleteResultItem) {
	o.Items = v
}

func (o OpenSearchAutocompleteResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableOpenSearchAutocompleteResponse struct {
	value *OpenSearchAutocompleteResponse
	isSet bool
}

func (v NullableOpenSearchAutocompleteResponse) Get() *OpenSearchAutocompleteResponse {
	return v.value
}

func (v *NullableOpenSearchAutocompleteResponse) Set(val *OpenSearchAutocompleteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenSearchAutocompleteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenSearchAutocompleteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenSearchAutocompleteResponse(val *OpenSearchAutocompleteResponse) *NullableOpenSearchAutocompleteResponse {
	return &NullableOpenSearchAutocompleteResponse{value: val, isSet: true}
}

func (v NullableOpenSearchAutocompleteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenSearchAutocompleteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


