/*
 * Geocoding and Search API v7
 *
 * This document describes the Geocoding and Search API.
 *
 * API version: 7.78
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package here

import (
	"encoding/json"
)

// Supplier struct for Supplier
type Supplier struct {
	// An identifier for the supplier.
	Id string `json:"id"`
}

// NewSupplier instantiates a new Supplier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupplier(id string, ) *Supplier {
	this := Supplier{}
	this.Id = id
	return &this
}

// NewSupplierWithDefaults instantiates a new Supplier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupplierWithDefaults() *Supplier {
	this := Supplier{}
	return &this
}

// GetId returns the Id field value
func (o *Supplier) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Supplier) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Supplier) SetId(v string) {
	o.Id = v
}

func (o Supplier) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableSupplier struct {
	value *Supplier
	isSet bool
}

func (v NullableSupplier) Get() *Supplier {
	return v.value
}

func (v *NullableSupplier) Set(val *Supplier) {
	v.value = val
	v.isSet = true
}

func (v NullableSupplier) IsSet() bool {
	return v.isSet
}

func (v *NullableSupplier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupplier(val *Supplier) *NullableSupplier {
	return &NullableSupplier{value: val, isSet: true}
}

func (v NullableSupplier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupplier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


