/*
 * Geocoding and Search API v7
 *
 * This document describes the Geocoding and Search API.
 *
 * API version: 7.78
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package here

import (
	"encoding/json"
)

// EvNameId struct for EvNameId
type EvNameId struct {
	// Any string value
	Name *string `json:"name,omitempty"`
	// Unique ID
	Id *string `json:"id,omitempty"`
}

// NewEvNameId instantiates a new EvNameId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvNameId() *EvNameId {
	this := EvNameId{}
	return &this
}

// NewEvNameIdWithDefaults instantiates a new EvNameId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvNameIdWithDefaults() *EvNameId {
	this := EvNameId{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EvNameId) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvNameId) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EvNameId) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EvNameId) SetName(v string) {
	o.Name = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EvNameId) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvNameId) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EvNameId) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EvNameId) SetId(v string) {
	o.Id = &v
}

func (o EvNameId) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableEvNameId struct {
	value *EvNameId
	isSet bool
}

func (v NullableEvNameId) Get() *EvNameId {
	return v.value
}

func (v *NullableEvNameId) Set(val *EvNameId) {
	v.value = val
	v.isSet = true
}

func (v NullableEvNameId) IsSet() bool {
	return v.isSet
}

func (v *NullableEvNameId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvNameId(val *EvNameId) *NullableEvNameId {
	return &NullableEvNameId{value: val, isSet: true}
}

func (v NullableEvNameId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvNameId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


