/*
 * Geocoding and Search API v7
 *
 * This document describes the Geocoding and Search API.
 *
 * API version: 7.78
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package here

import (
	"encoding/json"
)

// SupplierReference struct for SupplierReference
type SupplierReference struct {
	// Information about the supplier of this reference.
	Supplier Supplier `json:"supplier"`
	// Identifier of the place as provided by the supplier.
	Id string `json:"id"`
}

// NewSupplierReference instantiates a new SupplierReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupplierReference(supplier Supplier, id string, ) *SupplierReference {
	this := SupplierReference{}
	this.Supplier = supplier
	this.Id = id
	return &this
}

// NewSupplierReferenceWithDefaults instantiates a new SupplierReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupplierReferenceWithDefaults() *SupplierReference {
	this := SupplierReference{}
	return &this
}

// GetSupplier returns the Supplier field value
func (o *SupplierReference) GetSupplier() Supplier {
	if o == nil  {
		var ret Supplier
		return ret
	}

	return o.Supplier
}

// GetSupplierOk returns a tuple with the Supplier field value
// and a boolean to check if the value has been set.
func (o *SupplierReference) GetSupplierOk() (*Supplier, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Supplier, true
}

// SetSupplier sets field value
func (o *SupplierReference) SetSupplier(v Supplier) {
	o.Supplier = v
}

// GetId returns the Id field value
func (o *SupplierReference) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SupplierReference) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SupplierReference) SetId(v string) {
	o.Id = v
}

func (o SupplierReference) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["supplier"] = o.Supplier
	}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableSupplierReference struct {
	value *SupplierReference
	isSet bool
}

func (v NullableSupplierReference) Get() *SupplierReference {
	return v.value
}

func (v *NullableSupplierReference) Set(val *SupplierReference) {
	v.value = val
	v.isSet = true
}

func (v NullableSupplierReference) IsSet() bool {
	return v.isSet
}

func (v *NullableSupplierReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupplierReference(val *SupplierReference) *NullableSupplierReference {
	return &NullableSupplierReference{value: val, isSet: true}
}

func (v NullableSupplierReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupplierReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


