/*
 * Geocoding and Search API v7
 *
 * This document describes the Geocoding and Search API.
 *
 * API version: 7.78
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package here

import (
	"encoding/json"
)

// LookupResponse struct for LookupResponse
type LookupResponse struct {
	// The localized display name of this result item.
	Title string `json:"title"`
	// The unique identifier for the result item. This ID can be used for a Look Up by ID search as well.
	Id *string `json:"id,omitempty"`
	// ISO3 country code of the item political view (default for international). This response element is populated when the politicalView parameter is set in the query
	PoliticalView *string `json:"politicalView,omitempty"`
	// WARNING: The resultType values 'intersection' and 'postalCodePoint' are in BETA state
	ResultType *string `json:"resultType,omitempty"`
	// * PA - a Point Address represents an individual address as a point object. Point Addresses are coming from trusted sources.   We can say with high certainty that the address exists and at what position. A Point Address result contains two types of coordinates.   One is the access point (or navigation coordinates), which is the point to start or end a drive. The other point is the position or display point.   This point varies per source and country. The point can be the rooftop point, a point close to the building entry, or a point close to the building,   driveway or parking lot that belongs to the building. * interpolated - an interpolated address. These are approximate positions as a result of a linear interpolation based on address ranges.   Address ranges, especially in the USA, are typical per block. For interpolated addresses, we cannot say with confidence that the address exists in reality.   But the interpolation provides a good location approximation that brings people in most use cases close to the target location.   The access point of an interpolated address result is calculated based on the address range and the road geometry.   The position (display) point is pre-configured offset from the street geometry.   Compared to Point Addresses, interpolated addresses are less accurate.
	HouseNumberType *string `json:"houseNumberType,omitempty"`
	AddressBlockType *string `json:"addressBlockType,omitempty"`
	LocalityType *string `json:"localityType,omitempty"`
	AdministrativeAreaType *string `json:"administrativeAreaType,omitempty"`
	// If true, indicates that the requested house number was corrected to match the nearest known house number. This field is visible only when the value is true.
	HouseNumberFallback *bool `json:"houseNumberFallback,omitempty"`
	// Postal address of the result item.
	Address Address `json:"address"`
	// The coordinates (latitude, longitude) of a pin on a map corresponding to the searched place.
	Position *DisplayResponseCoordinate `json:"position,omitempty"`
	// Coordinates of the place you are navigating to (for example, driving or walking). This is a point on a road or in a parking lot.
	Access *[]AccessResponseCoordinate `json:"access,omitempty"`
	// The bounding box enclosing the geometric shape (area or line) that an individual result covers. `place` typed results have no `mapView`.
	MapView *MapView `json:"mapView,omitempty"`
	// The list of categories assigned to this place.
	Categories *[]Category `json:"categories,omitempty"`
	// The list of chains assigned to this place.
	Chains *[]Chain `json:"chains,omitempty"`
	// The list of supplier references available for this place.
	References *[]SupplierReference `json:"references,omitempty"`
	// The list of food types assigned to this place.
	FoodTypes *[]Category `json:"foodTypes,omitempty"`
	// Contact information like phone, email, WWW.
	Contacts *[]ContactInformation `json:"contacts,omitempty"`
	// A list of hours during which the place is open for business. This field is optional: When it is not present, it means that we are lacking data about the place opening hours. Days without opening hours have to be considered as closed.
	OpeningHours *[]OpeningHours `json:"openingHours,omitempty"`
	// BETA - Provides time zone information for this place. (rendered only if 'show=tz' is provided.)
	TimeZone *TimeZoneInfo `json:"timeZone,omitempty"`
	// Extended attributes section to contain detailed information for specific result types.
	Extended *ExtendedAttribute `json:"extended,omitempty"`
	// Phonemes for address and place names. (rendered only if 'show=phonemes' is provided.)
	Phonemes *PhonemesSection `json:"phonemes,omitempty"`
	// Street Details (only rendered if 'show=streetInfo' is provided.)
	StreetInfo *[]StreetInfo `json:"streetInfo,omitempty"`
	// Country Details (only rendered if 'show=countryInfo' is provided.)
	CountryInfo *CountryInfo `json:"countryInfo,omitempty"`
}

// NewLookupResponse instantiates a new LookupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLookupResponse(title string, address Address, ) *LookupResponse {
	this := LookupResponse{}
	this.Title = title
	this.Address = address
	return &this
}

// NewLookupResponseWithDefaults instantiates a new LookupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLookupResponseWithDefaults() *LookupResponse {
	this := LookupResponse{}
	return &this
}

// GetTitle returns the Title field value
func (o *LookupResponse) GetTitle() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *LookupResponse) SetTitle(v string) {
	o.Title = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LookupResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LookupResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LookupResponse) SetId(v string) {
	o.Id = &v
}

// GetPoliticalView returns the PoliticalView field value if set, zero value otherwise.
func (o *LookupResponse) GetPoliticalView() string {
	if o == nil || o.PoliticalView == nil {
		var ret string
		return ret
	}
	return *o.PoliticalView
}

// GetPoliticalViewOk returns a tuple with the PoliticalView field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetPoliticalViewOk() (*string, bool) {
	if o == nil || o.PoliticalView == nil {
		return nil, false
	}
	return o.PoliticalView, true
}

// HasPoliticalView returns a boolean if a field has been set.
func (o *LookupResponse) HasPoliticalView() bool {
	if o != nil && o.PoliticalView != nil {
		return true
	}

	return false
}

// SetPoliticalView gets a reference to the given string and assigns it to the PoliticalView field.
func (o *LookupResponse) SetPoliticalView(v string) {
	o.PoliticalView = &v
}

// GetResultType returns the ResultType field value if set, zero value otherwise.
func (o *LookupResponse) GetResultType() string {
	if o == nil || o.ResultType == nil {
		var ret string
		return ret
	}
	return *o.ResultType
}

// GetResultTypeOk returns a tuple with the ResultType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetResultTypeOk() (*string, bool) {
	if o == nil || o.ResultType == nil {
		return nil, false
	}
	return o.ResultType, true
}

// HasResultType returns a boolean if a field has been set.
func (o *LookupResponse) HasResultType() bool {
	if o != nil && o.ResultType != nil {
		return true
	}

	return false
}

// SetResultType gets a reference to the given string and assigns it to the ResultType field.
func (o *LookupResponse) SetResultType(v string) {
	o.ResultType = &v
}

// GetHouseNumberType returns the HouseNumberType field value if set, zero value otherwise.
func (o *LookupResponse) GetHouseNumberType() string {
	if o == nil || o.HouseNumberType == nil {
		var ret string
		return ret
	}
	return *o.HouseNumberType
}

// GetHouseNumberTypeOk returns a tuple with the HouseNumberType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetHouseNumberTypeOk() (*string, bool) {
	if o == nil || o.HouseNumberType == nil {
		return nil, false
	}
	return o.HouseNumberType, true
}

// HasHouseNumberType returns a boolean if a field has been set.
func (o *LookupResponse) HasHouseNumberType() bool {
	if o != nil && o.HouseNumberType != nil {
		return true
	}

	return false
}

// SetHouseNumberType gets a reference to the given string and assigns it to the HouseNumberType field.
func (o *LookupResponse) SetHouseNumberType(v string) {
	o.HouseNumberType = &v
}

// GetAddressBlockType returns the AddressBlockType field value if set, zero value otherwise.
func (o *LookupResponse) GetAddressBlockType() string {
	if o == nil || o.AddressBlockType == nil {
		var ret string
		return ret
	}
	return *o.AddressBlockType
}

// GetAddressBlockTypeOk returns a tuple with the AddressBlockType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetAddressBlockTypeOk() (*string, bool) {
	if o == nil || o.AddressBlockType == nil {
		return nil, false
	}
	return o.AddressBlockType, true
}

// HasAddressBlockType returns a boolean if a field has been set.
func (o *LookupResponse) HasAddressBlockType() bool {
	if o != nil && o.AddressBlockType != nil {
		return true
	}

	return false
}

// SetAddressBlockType gets a reference to the given string and assigns it to the AddressBlockType field.
func (o *LookupResponse) SetAddressBlockType(v string) {
	o.AddressBlockType = &v
}

// GetLocalityType returns the LocalityType field value if set, zero value otherwise.
func (o *LookupResponse) GetLocalityType() string {
	if o == nil || o.LocalityType == nil {
		var ret string
		return ret
	}
	return *o.LocalityType
}

// GetLocalityTypeOk returns a tuple with the LocalityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetLocalityTypeOk() (*string, bool) {
	if o == nil || o.LocalityType == nil {
		return nil, false
	}
	return o.LocalityType, true
}

// HasLocalityType returns a boolean if a field has been set.
func (o *LookupResponse) HasLocalityType() bool {
	if o != nil && o.LocalityType != nil {
		return true
	}

	return false
}

// SetLocalityType gets a reference to the given string and assigns it to the LocalityType field.
func (o *LookupResponse) SetLocalityType(v string) {
	o.LocalityType = &v
}

// GetAdministrativeAreaType returns the AdministrativeAreaType field value if set, zero value otherwise.
func (o *LookupResponse) GetAdministrativeAreaType() string {
	if o == nil || o.AdministrativeAreaType == nil {
		var ret string
		return ret
	}
	return *o.AdministrativeAreaType
}

// GetAdministrativeAreaTypeOk returns a tuple with the AdministrativeAreaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetAdministrativeAreaTypeOk() (*string, bool) {
	if o == nil || o.AdministrativeAreaType == nil {
		return nil, false
	}
	return o.AdministrativeAreaType, true
}

// HasAdministrativeAreaType returns a boolean if a field has been set.
func (o *LookupResponse) HasAdministrativeAreaType() bool {
	if o != nil && o.AdministrativeAreaType != nil {
		return true
	}

	return false
}

// SetAdministrativeAreaType gets a reference to the given string and assigns it to the AdministrativeAreaType field.
func (o *LookupResponse) SetAdministrativeAreaType(v string) {
	o.AdministrativeAreaType = &v
}

// GetHouseNumberFallback returns the HouseNumberFallback field value if set, zero value otherwise.
func (o *LookupResponse) GetHouseNumberFallback() bool {
	if o == nil || o.HouseNumberFallback == nil {
		var ret bool
		return ret
	}
	return *o.HouseNumberFallback
}

// GetHouseNumberFallbackOk returns a tuple with the HouseNumberFallback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetHouseNumberFallbackOk() (*bool, bool) {
	if o == nil || o.HouseNumberFallback == nil {
		return nil, false
	}
	return o.HouseNumberFallback, true
}

// HasHouseNumberFallback returns a boolean if a field has been set.
func (o *LookupResponse) HasHouseNumberFallback() bool {
	if o != nil && o.HouseNumberFallback != nil {
		return true
	}

	return false
}

// SetHouseNumberFallback gets a reference to the given bool and assigns it to the HouseNumberFallback field.
func (o *LookupResponse) SetHouseNumberFallback(v bool) {
	o.HouseNumberFallback = &v
}

// GetAddress returns the Address field value
func (o *LookupResponse) GetAddress() Address {
	if o == nil  {
		var ret Address
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetAddressOk() (*Address, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *LookupResponse) SetAddress(v Address) {
	o.Address = v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *LookupResponse) GetPosition() DisplayResponseCoordinate {
	if o == nil || o.Position == nil {
		var ret DisplayResponseCoordinate
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetPositionOk() (*DisplayResponseCoordinate, bool) {
	if o == nil || o.Position == nil {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *LookupResponse) HasPosition() bool {
	if o != nil && o.Position != nil {
		return true
	}

	return false
}

// SetPosition gets a reference to the given DisplayResponseCoordinate and assigns it to the Position field.
func (o *LookupResponse) SetPosition(v DisplayResponseCoordinate) {
	o.Position = &v
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *LookupResponse) GetAccess() []AccessResponseCoordinate {
	if o == nil || o.Access == nil {
		var ret []AccessResponseCoordinate
		return ret
	}
	return *o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetAccessOk() (*[]AccessResponseCoordinate, bool) {
	if o == nil || o.Access == nil {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *LookupResponse) HasAccess() bool {
	if o != nil && o.Access != nil {
		return true
	}

	return false
}

// SetAccess gets a reference to the given []AccessResponseCoordinate and assigns it to the Access field.
func (o *LookupResponse) SetAccess(v []AccessResponseCoordinate) {
	o.Access = &v
}

// GetMapView returns the MapView field value if set, zero value otherwise.
func (o *LookupResponse) GetMapView() MapView {
	if o == nil || o.MapView == nil {
		var ret MapView
		return ret
	}
	return *o.MapView
}

// GetMapViewOk returns a tuple with the MapView field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetMapViewOk() (*MapView, bool) {
	if o == nil || o.MapView == nil {
		return nil, false
	}
	return o.MapView, true
}

// HasMapView returns a boolean if a field has been set.
func (o *LookupResponse) HasMapView() bool {
	if o != nil && o.MapView != nil {
		return true
	}

	return false
}

// SetMapView gets a reference to the given MapView and assigns it to the MapView field.
func (o *LookupResponse) SetMapView(v MapView) {
	o.MapView = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *LookupResponse) GetCategories() []Category {
	if o == nil || o.Categories == nil {
		var ret []Category
		return ret
	}
	return *o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetCategoriesOk() (*[]Category, bool) {
	if o == nil || o.Categories == nil {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *LookupResponse) HasCategories() bool {
	if o != nil && o.Categories != nil {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []Category and assigns it to the Categories field.
func (o *LookupResponse) SetCategories(v []Category) {
	o.Categories = &v
}

// GetChains returns the Chains field value if set, zero value otherwise.
func (o *LookupResponse) GetChains() []Chain {
	if o == nil || o.Chains == nil {
		var ret []Chain
		return ret
	}
	return *o.Chains
}

// GetChainsOk returns a tuple with the Chains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetChainsOk() (*[]Chain, bool) {
	if o == nil || o.Chains == nil {
		return nil, false
	}
	return o.Chains, true
}

// HasChains returns a boolean if a field has been set.
func (o *LookupResponse) HasChains() bool {
	if o != nil && o.Chains != nil {
		return true
	}

	return false
}

// SetChains gets a reference to the given []Chain and assigns it to the Chains field.
func (o *LookupResponse) SetChains(v []Chain) {
	o.Chains = &v
}

// GetReferences returns the References field value if set, zero value otherwise.
func (o *LookupResponse) GetReferences() []SupplierReference {
	if o == nil || o.References == nil {
		var ret []SupplierReference
		return ret
	}
	return *o.References
}

// GetReferencesOk returns a tuple with the References field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetReferencesOk() (*[]SupplierReference, bool) {
	if o == nil || o.References == nil {
		return nil, false
	}
	return o.References, true
}

// HasReferences returns a boolean if a field has been set.
func (o *LookupResponse) HasReferences() bool {
	if o != nil && o.References != nil {
		return true
	}

	return false
}

// SetReferences gets a reference to the given []SupplierReference and assigns it to the References field.
func (o *LookupResponse) SetReferences(v []SupplierReference) {
	o.References = &v
}

// GetFoodTypes returns the FoodTypes field value if set, zero value otherwise.
func (o *LookupResponse) GetFoodTypes() []Category {
	if o == nil || o.FoodTypes == nil {
		var ret []Category
		return ret
	}
	return *o.FoodTypes
}

// GetFoodTypesOk returns a tuple with the FoodTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetFoodTypesOk() (*[]Category, bool) {
	if o == nil || o.FoodTypes == nil {
		return nil, false
	}
	return o.FoodTypes, true
}

// HasFoodTypes returns a boolean if a field has been set.
func (o *LookupResponse) HasFoodTypes() bool {
	if o != nil && o.FoodTypes != nil {
		return true
	}

	return false
}

// SetFoodTypes gets a reference to the given []Category and assigns it to the FoodTypes field.
func (o *LookupResponse) SetFoodTypes(v []Category) {
	o.FoodTypes = &v
}

// GetContacts returns the Contacts field value if set, zero value otherwise.
func (o *LookupResponse) GetContacts() []ContactInformation {
	if o == nil || o.Contacts == nil {
		var ret []ContactInformation
		return ret
	}
	return *o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetContactsOk() (*[]ContactInformation, bool) {
	if o == nil || o.Contacts == nil {
		return nil, false
	}
	return o.Contacts, true
}

// HasContacts returns a boolean if a field has been set.
func (o *LookupResponse) HasContacts() bool {
	if o != nil && o.Contacts != nil {
		return true
	}

	return false
}

// SetContacts gets a reference to the given []ContactInformation and assigns it to the Contacts field.
func (o *LookupResponse) SetContacts(v []ContactInformation) {
	o.Contacts = &v
}

// GetOpeningHours returns the OpeningHours field value if set, zero value otherwise.
func (o *LookupResponse) GetOpeningHours() []OpeningHours {
	if o == nil || o.OpeningHours == nil {
		var ret []OpeningHours
		return ret
	}
	return *o.OpeningHours
}

// GetOpeningHoursOk returns a tuple with the OpeningHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetOpeningHoursOk() (*[]OpeningHours, bool) {
	if o == nil || o.OpeningHours == nil {
		return nil, false
	}
	return o.OpeningHours, true
}

// HasOpeningHours returns a boolean if a field has been set.
func (o *LookupResponse) HasOpeningHours() bool {
	if o != nil && o.OpeningHours != nil {
		return true
	}

	return false
}

// SetOpeningHours gets a reference to the given []OpeningHours and assigns it to the OpeningHours field.
func (o *LookupResponse) SetOpeningHours(v []OpeningHours) {
	o.OpeningHours = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *LookupResponse) GetTimeZone() TimeZoneInfo {
	if o == nil || o.TimeZone == nil {
		var ret TimeZoneInfo
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetTimeZoneOk() (*TimeZoneInfo, bool) {
	if o == nil || o.TimeZone == nil {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *LookupResponse) HasTimeZone() bool {
	if o != nil && o.TimeZone != nil {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given TimeZoneInfo and assigns it to the TimeZone field.
func (o *LookupResponse) SetTimeZone(v TimeZoneInfo) {
	o.TimeZone = &v
}

// GetExtended returns the Extended field value if set, zero value otherwise.
func (o *LookupResponse) GetExtended() ExtendedAttribute {
	if o == nil || o.Extended == nil {
		var ret ExtendedAttribute
		return ret
	}
	return *o.Extended
}

// GetExtendedOk returns a tuple with the Extended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetExtendedOk() (*ExtendedAttribute, bool) {
	if o == nil || o.Extended == nil {
		return nil, false
	}
	return o.Extended, true
}

// HasExtended returns a boolean if a field has been set.
func (o *LookupResponse) HasExtended() bool {
	if o != nil && o.Extended != nil {
		return true
	}

	return false
}

// SetExtended gets a reference to the given ExtendedAttribute and assigns it to the Extended field.
func (o *LookupResponse) SetExtended(v ExtendedAttribute) {
	o.Extended = &v
}

// GetPhonemes returns the Phonemes field value if set, zero value otherwise.
func (o *LookupResponse) GetPhonemes() PhonemesSection {
	if o == nil || o.Phonemes == nil {
		var ret PhonemesSection
		return ret
	}
	return *o.Phonemes
}

// GetPhonemesOk returns a tuple with the Phonemes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetPhonemesOk() (*PhonemesSection, bool) {
	if o == nil || o.Phonemes == nil {
		return nil, false
	}
	return o.Phonemes, true
}

// HasPhonemes returns a boolean if a field has been set.
func (o *LookupResponse) HasPhonemes() bool {
	if o != nil && o.Phonemes != nil {
		return true
	}

	return false
}

// SetPhonemes gets a reference to the given PhonemesSection and assigns it to the Phonemes field.
func (o *LookupResponse) SetPhonemes(v PhonemesSection) {
	o.Phonemes = &v
}

// GetStreetInfo returns the StreetInfo field value if set, zero value otherwise.
func (o *LookupResponse) GetStreetInfo() []StreetInfo {
	if o == nil || o.StreetInfo == nil {
		var ret []StreetInfo
		return ret
	}
	return *o.StreetInfo
}

// GetStreetInfoOk returns a tuple with the StreetInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetStreetInfoOk() (*[]StreetInfo, bool) {
	if o == nil || o.StreetInfo == nil {
		return nil, false
	}
	return o.StreetInfo, true
}

// HasStreetInfo returns a boolean if a field has been set.
func (o *LookupResponse) HasStreetInfo() bool {
	if o != nil && o.StreetInfo != nil {
		return true
	}

	return false
}

// SetStreetInfo gets a reference to the given []StreetInfo and assigns it to the StreetInfo field.
func (o *LookupResponse) SetStreetInfo(v []StreetInfo) {
	o.StreetInfo = &v
}

// GetCountryInfo returns the CountryInfo field value if set, zero value otherwise.
func (o *LookupResponse) GetCountryInfo() CountryInfo {
	if o == nil || o.CountryInfo == nil {
		var ret CountryInfo
		return ret
	}
	return *o.CountryInfo
}

// GetCountryInfoOk returns a tuple with the CountryInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LookupResponse) GetCountryInfoOk() (*CountryInfo, bool) {
	if o == nil || o.CountryInfo == nil {
		return nil, false
	}
	return o.CountryInfo, true
}

// HasCountryInfo returns a boolean if a field has been set.
func (o *LookupResponse) HasCountryInfo() bool {
	if o != nil && o.CountryInfo != nil {
		return true
	}

	return false
}

// SetCountryInfo gets a reference to the given CountryInfo and assigns it to the CountryInfo field.
func (o *LookupResponse) SetCountryInfo(v CountryInfo) {
	o.CountryInfo = &v
}

func (o LookupResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["title"] = o.Title
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.PoliticalView != nil {
		toSerialize["politicalView"] = o.PoliticalView
	}
	if o.ResultType != nil {
		toSerialize["resultType"] = o.ResultType
	}
	if o.HouseNumberType != nil {
		toSerialize["houseNumberType"] = o.HouseNumberType
	}
	if o.AddressBlockType != nil {
		toSerialize["addressBlockType"] = o.AddressBlockType
	}
	if o.LocalityType != nil {
		toSerialize["localityType"] = o.LocalityType
	}
	if o.AdministrativeAreaType != nil {
		toSerialize["administrativeAreaType"] = o.AdministrativeAreaType
	}
	if o.HouseNumberFallback != nil {
		toSerialize["houseNumberFallback"] = o.HouseNumberFallback
	}
	if true {
		toSerialize["address"] = o.Address
	}
	if o.Position != nil {
		toSerialize["position"] = o.Position
	}
	if o.Access != nil {
		toSerialize["access"] = o.Access
	}
	if o.MapView != nil {
		toSerialize["mapView"] = o.MapView
	}
	if o.Categories != nil {
		toSerialize["categories"] = o.Categories
	}
	if o.Chains != nil {
		toSerialize["chains"] = o.Chains
	}
	if o.References != nil {
		toSerialize["references"] = o.References
	}
	if o.FoodTypes != nil {
		toSerialize["foodTypes"] = o.FoodTypes
	}
	if o.Contacts != nil {
		toSerialize["contacts"] = o.Contacts
	}
	if o.OpeningHours != nil {
		toSerialize["openingHours"] = o.OpeningHours
	}
	if o.TimeZone != nil {
		toSerialize["timeZone"] = o.TimeZone
	}
	if o.Extended != nil {
		toSerialize["extended"] = o.Extended
	}
	if o.Phonemes != nil {
		toSerialize["phonemes"] = o.Phonemes
	}
	if o.StreetInfo != nil {
		toSerialize["streetInfo"] = o.StreetInfo
	}
	if o.CountryInfo != nil {
		toSerialize["countryInfo"] = o.CountryInfo
	}
	return json.Marshal(toSerialize)
}

type NullableLookupResponse struct {
	value *LookupResponse
	isSet bool
}

func (v NullableLookupResponse) Get() *LookupResponse {
	return v.value
}

func (v *NullableLookupResponse) Set(val *LookupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLookupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLookupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLookupResponse(val *LookupResponse) *NullableLookupResponse {
	return &NullableLookupResponse{value: val, isSet: true}
}

func (v NullableLookupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLookupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


